import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import { Box } from "@chakra-ui/react";
import ReduxProvider from "@/redux/ReduxProvider";

const roboto = Roboto({
  subsets: ["latin", "latin-ext"],
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto_mono.className} antialiased p-0 m-0`}
      >
        <ReduxProvider>
          <Providers>
            <Box minH="100vh" bg={{ _light: "white", _dark: "black" }}>
              <Navbar />
              {children}
            </Box>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
